/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dal.DanhSach_DAL;
import dto.DatSach_DTO;
import dto.Sach_DTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FrmSachDaXoa extends javax.swing.JFrame {
    DefaultTableModel model = null; //khởi tạo hàm Model để hiển thị  lên table
    ArrayList<DatSach_DTO> DS_DatSach = null;
    ArrayList<Sach_DTO> DS_Sach = null;
    Sach_DTO selectSach= null;
    

    
    public FrmSachDaXoa() {
        initComponents();
        model=(DefaultTableModel) tblSach.getModel();
        hienthiDatSach();
    }
    
    public void hienthisach(){// hàm để hiển thị thông tin sách đã xóa trong thư mục form đặt sách qua thư mục form sách đã xóa
        model.setRowCount(0);
        //hàm này đang nghiên cứu
    }
    
    void hienthiDatSach(){
        model.setRowCount(0);
        for(Sach_DTO DS:DS_Sach){
            model.addRow(new Object[]{//khai báo từng biến có trong giao diện
                DS.getMaSach(),
                DS.getTenSach(),
                DS.getTheLoai(),
                DS.getTacGia(),
                DS.getNhaXuatBan(),
                DS.getNgayXuatBan(),
                DS.getSoLuong(),
                DS.getGiaThanh(),
            
            });
        }    
            
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnXoaAll = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Magneto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete List Book");

        btnXoaAll.setText("Xóa Tất Cả");
        btnXoaAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaAllMouseClicked(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "Thể Loại", "Tác Giả", "Nhà Xuất Bản", "Ngày Xuất Bản", "Số Lượng", "Giá Thành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1223, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaAll, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaAll)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        int index = tblSach.getSelectedRow();// khai báo phần giao diện để khi click chuột vào
        if (index == -1) {// nếu phần index bằng 0 thì nó sẽ return đi vì trong bảng giao diện ko dc bằng 0
            return;
        }
        selectSach= null;// sách hiện tại = null
        // đưa toàn bộ giá trị của thằng được chọn lên trên các trường dữ liệu
        // hàm khi click vào 1 quyển sách thì nó sẽ xóa
        if(selectSach==null){// nếu hàm select = null thì nó sẽ trả về return
            return;
        }
        DanhSach_DAL.xoaSach(selectSach);//
        hienthiDatSach();// khi xóa 1 quyển sách thì nó sẽ hiển thị lên màn hình giao diện
        
        selectSach=null;// tại đây selectDatSach=null
        //hàm xóa 1 quyển sách đã đặt
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnXoaAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaAllMouseClicked
         if (selectSach!=null) {// nếu selectSach1 khác null thì nó sẽ trả về phần sách đã xóa
            DanhSach_DAL.xoaSach(selectSach);
            selectSach = null;
            hienthiDatSach();//hàm xóa tất cả sách trong thư mục
        }
    }//GEN-LAST:event_btnXoaAllMouseClicked

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        int index = tblSach.getSelectedRow();//khai báo biến index là bảng tblsach. Để khi click chuột vào thì nó sẽ sử dụng dc
        if (index == -1) {
            return;
        }
        selectSach= null;// giá trị select = null
        // đưa toàn bộ giá trị của thằng được chọn lên trên các trường dữ liệu
       
    }//GEN-LAST:event_tblSachMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSach;
    // End of variables declaration//GEN-END:variables
}
